version: '3.7'
services:
  postgres:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=${PG_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${PG_DATABASE_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE_NAME}
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '${PG_DATABASE_PORT}:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
